### ISSUE TITLE
Is it ready to use?

### ISSUE THREAD

**Issue by Slin-nilS** [konradwalsh/ha-meshcentral-addon#1]
Hi,

Is the plugin ready to use? Or is it still on working?
["Simply copy the contents of this repository to the base directory of the add-on you are developing."](https://github.com/konradwalsh/ha-meshcentral-addon#readme)
Which directory do you mean?

Greedings
Nils

**Comment by konradwalsh** [comment]
Hey Nils
Working hard on it.. for now its not.. sorry.. 

I have issues mostly with HA dev environment .. 

will update here once its working

**Comment by Slin-nilS** [comment]
Hey @konradwalsh 
ok. Thank you for your fast Answer :)
Good luck.

Greedings
Nils
